# Generated by Django 4.2.7 on 2024-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('etiqueta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('temp_acumulado', models.DecimalField(
                    decimal_places=6, max_digits=20, null=True, blank=True, default=0)),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.IntegerField(default=2)),
                ('prioridad', models.IntegerField(default=1)),
                ('categoria', models.IntegerField(default=1)),
                ('sitio', models.IntegerField(default=0)),
                ('departamento', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField(null=True, blank=True)),
                ('fecha_finalizacion', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'db_table': 'tareas_tarea',
            },
        ),
    ]
