# Generated by Django 4.2.7 on 2024-06-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=400)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareas_comentario',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tareas_departamento',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tareas_sitio',
            },
        ),
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Redes'), (3, 'Soporte')], default=1),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Pausada'), (3, 'Finalizada')], default=2),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=400)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tareas.comentario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tareas.tarea')),
            ],
            options={
                'db_table': 'tareas_archivo',
            },
        ),
    ]
