# Generated by Django 4.2.7 on 2024-01-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0003_alter_tarea_categoria_alter_tarea_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Pausada'), (3, 'Finalizada')], default=2),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_modificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
