# Generated by Django 4.2.7 on 2024-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0005_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='temp_acumulado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
