# Generated by Django 4.2.7 on 2024-01-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0006_tarea_temp_acumulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='temp_acumulado',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
