# Generated by Django 4.2.7 on 2023-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=16)),
                ('comentario', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fehcaModificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
