# Generated by Django 4.2.7 on 2023-11-09 19:29

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MacAmb', '0002_alter_mac_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mac',
            name='mac',
            field=macaddress.fields.MACAddressField(blank=True, integer=True, null=True),
        ),
        migrations.AlterField(
            model_name='mac',
            name='comentario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mac',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
