# Generated by Django 4.2.7 on 2023-11-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MacAmb', '0003_mac_mac_alter_mac_comentario_alter_mac_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mac',
            old_name='fehcaModificacion',
            new_name='fechaModificacion',
        ),
    ]
