# Generated by Django 4.2.7 on 2023-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MacAmb', '0004_rename_fehcamodificacion_mac_fechamodificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mac',
            old_name='fechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='mac',
            old_name='fechaModificacion',
            new_name='fecha_modificacion',
        ),
        migrations.AlterModelTable(
            name='mac',
            table='mac_abm_mac',
        ),
    ]
