# Generated by Django 4.2.7 on 2023-12-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MacAmb', '0005_rename_fechacreacion_mac_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mac',
            old_name='fecha_modificacion',
            new_name='fechamodificacion',
        ),
    ]
