# Generated by Django 4.2.7 on 2023-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MacAmb', '0007_rename_fechamodificacion_mac_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mac',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
    ]
